// GENERATED by kjui_tools TabviewComponent.generate (jsonui-cli 856c7740) for the badge
// measurement: tabs Home (no badge), Inbox (3), News ("NEW"), Chat (@{unread}),
// resource icons from library-dynamic. The body of each function is the
// emitter's output verbatim; only the wrapper, the imports and the data class
// are written by hand. Regenerate with the emitter at that commit for the same four tabs.
package com.kotlinjsonui.dynamic

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.semantics.stateDescription

data class TabBadgeProbeData(val unread: Int? = null)

@Composable
fun GeneratedTabBadgeLabelled(data: TabBadgeProbeData) {
    // TabView with NavigationBar
    var selectedTab by remember { mutableStateOf(0) }

    Scaffold(
        bottomBar = {
            NavigationBar(
            ) {
                NavigationBarItem(
                    selected = selectedTab == 0,
                    onClick = { selectedTab = 0 },
                    icon = {
                        Icon(
                            painter = painterResource(R.drawable.ic_home_filled),
                            contentDescription = "Home"
                        )
                    },
                    label = { Text("Home") },
                    colors = NavigationBarItemDefaults.colors(
                        selectedIconColor = MaterialTheme.colorScheme.primary,
                        selectedTextColor = MaterialTheme.colorScheme.primary,
                        unselectedIconColor = MaterialTheme.colorScheme.onSurfaceVariant,
                        unselectedTextColor = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                )
                NavigationBarItem(
                    selected = selectedTab == 1,
                    onClick = { selectedTab = 1 },
                    modifier = Modifier.semantics { stateDescription = "3" },
                    icon = {
                        BadgedBox(badge = { Badge { Text("3") } }) {
                            Icon(
                                painter = painterResource(R.drawable.ic_circle_filled),
                                contentDescription = "Inbox"
                            )
                        }
                    },
                    label = { Text("Inbox") },
                    colors = NavigationBarItemDefaults.colors(
                        selectedIconColor = MaterialTheme.colorScheme.primary,
                        selectedTextColor = MaterialTheme.colorScheme.primary,
                        unselectedIconColor = MaterialTheme.colorScheme.onSurfaceVariant,
                        unselectedTextColor = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                )
                NavigationBarItem(
                    selected = selectedTab == 2,
                    onClick = { selectedTab = 2 },
                    modifier = Modifier.semantics { stateDescription = "NEW" },
                    icon = {
                        BadgedBox(badge = { Badge { Text("NEW") } }) {
                            Icon(
                                painter = painterResource(R.drawable.ic_favorite_filled),
                                contentDescription = "News"
                            )
                        }
                    },
                    label = { Text("News") },
                    colors = NavigationBarItemDefaults.colors(
                        selectedIconColor = MaterialTheme.colorScheme.primary,
                        selectedTextColor = MaterialTheme.colorScheme.primary,
                        unselectedIconColor = MaterialTheme.colorScheme.onSurfaceVariant,
                        unselectedTextColor = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                )
                val badge3: String? = when (val v: Any? = data.unread) { is Number -> if (v.toInt() > 0) { if (v is Int || v is Long || v.toDouble() % 1.0 != 0.0) v.toString() else v.toLong().toString() } else null; is String -> v.ifEmpty { null }; else -> null }
                NavigationBarItem(
                    selected = selectedTab == 3,
                    onClick = { selectedTab = 3 },
                    modifier = if (badge3 != null) Modifier.semantics { stateDescription = badge3 } else Modifier,
                    icon = {
                        if (badge3 != null) {
                            BadgedBox(badge = { Badge { Text(badge3) } }) {
                                Icon(
                                    painter = painterResource(R.drawable.ic_check_circle_filled),
                                    contentDescription = "Chat"
                                )
                            }
                        } else {
                            Icon(
                                painter = painterResource(R.drawable.ic_check_circle_filled),
                                contentDescription = "Chat"
                            )
                        }
                    },
                    label = { Text("Chat") },
                    colors = NavigationBarItemDefaults.colors(
                        selectedIconColor = MaterialTheme.colorScheme.primary,
                        selectedTextColor = MaterialTheme.colorScheme.primary,
                        unselectedIconColor = MaterialTheme.colorScheme.onSurfaceVariant,
                        unselectedTextColor = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                )
            }
        }
    ) { innerPadding ->
        Box(modifier = Modifier.padding(bottom = innerPadding.calculateBottomPadding())) {
            CompositionLocalProvider(
                LocalSafeAreaConfig provides SafeAreaConfig(ignoreBottom = true)
            ) {
                when (selectedTab) {
                    0 -> {
                        Text("Home content")
                    }
                    1 -> {
                        Text("Inbox content")
                    }
                    2 -> {
                        Text("News content")
                    }
                    3 -> {
                        Text("Chat content")
                    }
                }
            }
        }
    }
}

@Composable
fun GeneratedTabBadgeUnlabelled(data: TabBadgeProbeData) {
    // TabView with NavigationBar
    var selectedTab by remember { mutableStateOf(0) }

    Scaffold(
        bottomBar = {
            NavigationBar(
            ) {
                NavigationBarItem(
                    selected = selectedTab == 0,
                    onClick = { selectedTab = 0 },
                    icon = {
                        Icon(
                            painter = painterResource(R.drawable.ic_home_filled),
                            contentDescription = "Home"
                        )
                    },
                    colors = NavigationBarItemDefaults.colors(
                        selectedIconColor = MaterialTheme.colorScheme.primary,
                        selectedTextColor = MaterialTheme.colorScheme.primary,
                        unselectedIconColor = MaterialTheme.colorScheme.onSurfaceVariant,
                        unselectedTextColor = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                )
                NavigationBarItem(
                    selected = selectedTab == 1,
                    onClick = { selectedTab = 1 },
                    icon = {
                        BadgedBox(badge = { Badge { Text("3") } }) {
                            Icon(
                                painter = painterResource(R.drawable.ic_circle_filled),
                                contentDescription = "Inbox"
                            )
                        }
                    },
                    colors = NavigationBarItemDefaults.colors(
                        selectedIconColor = MaterialTheme.colorScheme.primary,
                        selectedTextColor = MaterialTheme.colorScheme.primary,
                        unselectedIconColor = MaterialTheme.colorScheme.onSurfaceVariant,
                        unselectedTextColor = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                )
                NavigationBarItem(
                    selected = selectedTab == 2,
                    onClick = { selectedTab = 2 },
                    icon = {
                        BadgedBox(badge = { Badge { Text("NEW") } }) {
                            Icon(
                                painter = painterResource(R.drawable.ic_favorite_filled),
                                contentDescription = "News"
                            )
                        }
                    },
                    colors = NavigationBarItemDefaults.colors(
                        selectedIconColor = MaterialTheme.colorScheme.primary,
                        selectedTextColor = MaterialTheme.colorScheme.primary,
                        unselectedIconColor = MaterialTheme.colorScheme.onSurfaceVariant,
                        unselectedTextColor = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                )
                val badge3: String? = when (val v: Any? = data.unread) { is Number -> if (v.toInt() > 0) { if (v is Int || v is Long || v.toDouble() % 1.0 != 0.0) v.toString() else v.toLong().toString() } else null; is String -> v.ifEmpty { null }; else -> null }
                NavigationBarItem(
                    selected = selectedTab == 3,
                    onClick = { selectedTab = 3 },
                    icon = {
                        if (badge3 != null) {
                            BadgedBox(badge = { Badge { Text(badge3) } }) {
                                Icon(
                                    painter = painterResource(R.drawable.ic_check_circle_filled),
                                    contentDescription = "Chat"
                                )
                            }
                        } else {
                            Icon(
                                painter = painterResource(R.drawable.ic_check_circle_filled),
                                contentDescription = "Chat"
                            )
                        }
                    },
                    colors = NavigationBarItemDefaults.colors(
                        selectedIconColor = MaterialTheme.colorScheme.primary,
                        selectedTextColor = MaterialTheme.colorScheme.primary,
                        unselectedIconColor = MaterialTheme.colorScheme.onSurfaceVariant,
                        unselectedTextColor = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                )
            }
        }
    ) { innerPadding ->
        Box(modifier = Modifier.padding(bottom = innerPadding.calculateBottomPadding())) {
            CompositionLocalProvider(
                LocalSafeAreaConfig provides SafeAreaConfig(ignoreBottom = true)
            ) {
                when (selectedTab) {
                    0 -> {
                        Text("Home content")
                    }
                    1 -> {
                        Text("Inbox content")
                    }
                    2 -> {
                        Text("News content")
                    }
                    3 -> {
                        Text("Chat content")
                    }
                }
            }
        }
    }
}
