package com.example.kotlinjsonui.sample.dynamic.components.extensions

import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import com.google.gson.JsonObject
import com.google.gson.JsonElement
import androidx.compose.ui.text.style.TextAlign
import com.kotlinjsonui.dynamic.helpers.ModifierBuilder
import com.example.kotlinjsonui.sample.extensions.SampleCard

/**
 * Dynamic wrapper for SampleCard component
 * Auto-generated by kjui converter generator
 */
object DynamicSampleCardComponent {
    @Composable
    fun create(
        json: JsonObject,
        data: Map<String, Any> = emptyMap()
    ) {
        val context = LocalContext.current

        // Parse attributes
        val title = parseString(json.get("title"), data)
        val subtitle = parseString(json.get("subtitle"), data)
        val count = parseInt(json.get("count"), data)

        // Build modifier
        val modifier = ModifierBuilder.buildModifier(json, data, context = context)
        
        // Call the custom component with children
        SampleCard(
            title = title ?: "",
            subtitle = subtitle ?: "",
            count = count ?: 0,
            modifier = modifier
        ) {
            // Process children
            val children = json.get("children")?.asJsonArray ?: json.get("child")?.asJsonArray
            children?.forEach { childJson ->
                if (childJson.isJsonObject) {
                    com.kotlinjsonui.dynamic.DynamicView(
                        json = childJson.asJsonObject,
                        data = data
                    )
                }
            }
        }
    }
    
private fun parseString(element: com.google.gson.JsonElement?, data: Map<String, Any>): String? {
    if (element == null || element.isJsonNull) return null
    
    val value = element.asString
    
    // Check for binding
    if (value.startsWith("@{") && value.endsWith("}")) {
        val propertyName = value.substring(2, value.length - 1)
        return data[propertyName]?.toString()
    }
    
    return value
}


private fun parseInt(element: com.google.gson.JsonElement?, data: Map<String, Any>): Int? {
    if (element == null || element.isJsonNull) return null
    
    if (element.isJsonPrimitive) {
        val primitive = element.asJsonPrimitive
        if (primitive.isNumber) {
            return primitive.asInt
        } else if (primitive.isString) {
            val value = primitive.asString
            // Check for binding
            if (value.startsWith("@{") && value.endsWith("}")) {
                val propertyName = value.substring(2, value.length - 1)
                return (data[propertyName] as? Number)?.toInt()
            }
            return value.toIntOrNull()
        }
    }
    
    return null
}

}
