package com.example.kotlinjsonui.sample

import androidx.compose.runtime.Composable
import com.google.gson.JsonObject
import com.kotlinjsonui.core.Configuration
import com.example.kotlinjsonui.sample.dynamic.DynamicComponentRegistry

/**
 * Debug-only initializer for custom components in dynamic mode
 * Auto-generated by kjui converter generator
 */
object DynamicComponentInitializer {
    
    /**
     * Register custom component handler for dynamic mode
     * This is only available in debug builds where DynamicComponentRegistry exists
     */
    fun initialize() {
        Configuration.customComponentHandler = { type, json, data ->
            DynamicComponentRegistry.createCustomComponent(type, json, data)
        }
    }
}
