// Pasted from what `kjui build` (kjui_tools of jsonui-cli rel/v1.8.121 = 74bdbfeb) emits for four
// Segments with a `valueChange` — alone (segv…) and beside an onValueChange (segw…), unbound and bound —
// for SegmentValueChangeProbeTest (ticket control-onclick-is-called-differently-on-every-path). Changed
// from the output: the package (com.kotlinjsonui.probe.* → com.kotlinjsonui.conformance.valuechange) and
// the unused `import com.kotlinjsonui.probe.R`.
// Generated by kjui_tools - DO NOT EDIT between GENERATED_CODE markers
package com.kotlinjsonui.conformance.valuechange

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update

class SegmentValueChangeViewModel(application: Application) : AndroidViewModel(application) {
    // JSON file reference for hot reload
    val jsonFileName = "segment_value_change"

    // Data model
    private val _data = MutableStateFlow(SegmentValueChangeData())
    val data: StateFlow<SegmentValueChangeData> = _data.asStateFlow()

    // >>> GENERATED_CODE_START
    // Auto-generated updateData function - updated by 'kjui build'
    @Suppress("UNCHECKED_CAST")
    fun updateData(updates: Map<String, Any>) {
        _data.update { current ->
            var updated = current
            updates.forEach { (key, value) ->
                updated = when (key) {
                    "onSegvuC" -> updated.copy(onSegvuC = value as? (() -> Unit)? ?: updated.onSegvuC)
                    "onSegvuV" -> updated.copy(onSegvuV = value as? (() -> Unit)? ?: updated.onSegvuV)
                    "onSegvbC" -> updated.copy(onSegvbC = value as? (() -> Unit)? ?: updated.onSegvbC)
                    "onSegvbV" -> updated.copy(onSegvbV = value as? (() -> Unit)? ?: updated.onSegvbV)
                    "onSegwuV" -> updated.copy(onSegwuV = value as? (() -> Unit)? ?: updated.onSegwuV)
                    "onSegwuC" -> updated.copy(onSegwuC = value as? (() -> Unit)? ?: updated.onSegwuC)
                    "onSegwuX" -> updated.copy(onSegwuX = value as? (() -> Unit)? ?: updated.onSegwuX)
                    "onSegwbV" -> updated.copy(onSegwbV = value as? (() -> Unit)? ?: updated.onSegwbV)
                    "onSegwbC" -> updated.copy(onSegwbC = value as? (() -> Unit)? ?: updated.onSegwbC)
                    "onSegwbX" -> updated.copy(onSegwbX = value as? (() -> Unit)? ?: updated.onSegwbX)
                    "segvbIdx" -> updated.copy(segvbIdx = (value as? Number)?.toInt() ?: updated.segvbIdx)
                    "segwbIdx" -> updated.copy(segwbIdx = (value as? Number)?.toInt() ?: updated.segwbIdx)
                    else -> updated
                }
            }
            updated
        }
    }
    // >>> GENERATED_CODE_END

    // Add your custom action handlers below
    fun onGetStarted() {
        // Handle button tap
    }
}
