package com.example.kotlinjsonui.sample.extensions

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.BoxScope
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier

/**
 * Custom SampleCard component
 * Generated by kjui converter generator
 * 
 * Regenerate with:
 * kjui g converter SampleCard --container --attr title:String --attr subtitle:String --attr count:Int
 */
@Composable
fun SampleCard(
    title: String = "",
    subtitle: String = "",
    count: Int = 0,
    modifier: Modifier = Modifier,
    content: @Composable BoxScope.() -> Unit
) {
    Box(
        modifier = modifier
    ) {
        // Custom container implementation
        content()
    }
}
