package com.kotlinjsonui.dynamic.components

import com.google.gson.JsonElement
import com.google.gson.JsonObject
import com.google.gson.JsonParser
import com.kotlinjsonui.dynamic.BindFold
import com.kotlinjsonui.dynamic.TypedAttrs
import com.kotlinjsonui.dynamic.generated.CheckBoxAttributes
import com.kotlinjsonui.dynamic.generated.JsonUIBindPrimaryValue
import com.kotlinjsonui.dynamic.generated.ProgressAttributes
import com.kotlinjsonui.dynamic.generated.RadioAttributes
import com.kotlinjsonui.dynamic.generated.TextFieldAttributes
import com.kotlinjsonui.dynamic.generated.TextViewAttributes
import com.kotlinjsonui.dynamic.generated.SegmentAttributes
import com.kotlinjsonui.dynamic.generated.SelectBoxAttributes
import com.kotlinjsonui.dynamic.generated.SliderAttributes
import com.kotlinjsonui.dynamic.generated.SwitchAttributes
import com.kotlinjsonui.dynamic.generated.ToggleAttributes
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * `bind` beside a component's own value attribute (jsonui-cli
 * `shared/core/bind_fold_vectors.json`, copied byte-identical into
 * src/test/resources; CI's vendored-fixture step compares the copy). The jui
 * normalizer rewrites each case's `node` to its `expect`; DynamicView folds a
 * layout the normalizer did not fold the same way (BindFold, on the generated
 * JsonUIBindPrimaryValue — generated by jsonui-cli's attr codegen, vendored
 * as BindPrimaryValue.kt; the table SwiftJsonUI's fold and the normalizer
 * read), so no component reads `bind`.
 */
class BindFoldVectorsTest {

    private val vectors: JsonObject by lazy {
        val stream = requireNotNull(
            javaClass.classLoader?.getResourceAsStream("bind_fold_vectors.json")
        ) { "bind_fold_vectors.json missing from test resources" }
        stream.reader(Charsets.UTF_8).use { JsonParser.parseReader(it).asJsonObject }
    }

    private fun json(s: String): JsonObject = JsonParser.parseString(s).asJsonObject

    private fun fold(node: JsonObject): JsonObject = BindFold.fold(node, node.get("type").asString)

    @Test
    fun everyCaseFoldsToItsExpectedNode() {
        val cases = vectors.getAsJsonArray("cases").map { it.asJsonObject }
        assertTrue("the table has fewer cases than it did (18)", cases.size >= 18)
        val found = cases.mapNotNull { case ->
            val node = case.getAsJsonObject("node")
            val got = fold(node.deepCopy())
            if (got == case.getAsJsonObject("expect")) null else "${case.get("name").asString}: $got"
        }
        assertEquals(found.joinToString("\n"), emptyList<String>(), found)
    }

    @Test
    fun theFoldLeavesTheCallersNodeAsItWas_andANodeWithoutBindIsTheSameObject() {
        val node = json("""{"type": "Switch", "bind": "@{on}"}""")
        fold(node)
        assertEquals(json("""{"type": "Switch", "bind": "@{on}"}"""), node)
        val plain = json("""{"type": "Switch", "isOn": true}""")
        assertTrue(fold(plain) === plain)
    }

    /**
     * `attributes_for_cases`: the table itself (JsonUIBindPrimaryValue
     * .attributesFor), as the normalizer and the shared validator answer it.
     */
    @Test
    fun everyAttributesForCase() {
        val cases = vectors.getAsJsonArray("attributes_for_cases").map { it.asJsonObject }
        assertTrue("the table has fewer attributes_for cases than it did (9)", cases.size >= 9)
        for (case in cases) {
            assertEquals(
                case.get("name").asString,
                case.getAsJsonArray("expect").map { it.asString },
                JsonUIBindPrimaryValue.attributesFor(case.get("type").asString, TypedAttrs.toAttrMap(case.getAsJsonObject("node"))),
            )
        }
    }

    /**
     * `style_cases`: the fold is on the node drawn — its style merged first
     * (DynamicStyleLoader.applyStyle: the style's entries, then the node's,
     * which win; `style` itself is not kept) — so a style's lone bind is
     * folded, and a style's own value makes a layout bind ignored.
     */
    @Test
    fun everyStyleCaseIsDrawnAsTheTableSays() {
        val cases = vectors.getAsJsonArray("style_cases").map { it.asJsonObject }
        assertTrue("the table has fewer style cases than it did (2)", cases.size >= 2)
        for (case in cases) {
            val node = case.getAsJsonObject("node")
            val style = case.getAsJsonObject("styles").getAsJsonObject(node.get("style").asString)
            val merged = JsonObject()
            for ((k, v) in style.entrySet()) merged.add(k, v)
            for ((k, v) in node.entrySet()) if (k != "style") merged.add(k, v)
            assertEquals(case.get("name").asString, case.getAsJsonObject("drawn"), fold(merged))
        }
    }

    // --- the fold's result reaches each component ---------------------------

    /** What a component acts on: the key its value is bound to, and the value it draws. */
    data class Reading(val key: String?, val value: Any?)

    private fun isDate(node: JsonObject) = node.get("selectItemType")?.asString == "Date"

    /** The component's own reading (the functions its create() calls) of the node DynamicView hands it. */
    private fun read(node: JsonObject, data: Map<String, Any>): Reading {
        val m = TypedAttrs.toAttrMap(node)
        return when (node.get("type").asString) {
            "Switch" -> SwitchAttributes.parse(m).let { a ->
                val key = DynamicSwitchComponent.resolveBindingVariable(a)
                Reading(key, DynamicSwitchComponent.resolveCheckedState(a, data, key))
            }
            "Toggle" -> ToggleAttributes.parse(m).let { a ->
                val key = DynamicToggleComponent.bindingVariableOf(a)
                Reading(key, DynamicToggleComponent.checkedOf(a, data, key))
            }
            "CheckBox", "Check" -> CheckBoxAttributes.parse(m).let { a ->
                val key = DynamicCheckBoxComponent.resolveBindingVariable(a)
                Reading(key, DynamicCheckBoxComponent.resolveCheckedState(a, data, key))
            }
            "Slider" -> SliderAttributes.parse(m).let { a ->
                val key = DynamicSliderComponent.bindingVariableOf(a)
                Reading(key, DynamicSliderComponent.valueOf(a, data, key, 0f, 1f))
            }
            "Segment" -> SegmentAttributes.parse(m).let { a ->
                val key = DynamicSegmentComponent.bindingVariableOf(a)
                Reading(key, DynamicSegmentComponent.selectedIndexOf(a, data, key))
            }
            "Progress" -> ProgressAttributes.parse(m).let { a ->
                val key = DynamicProgressComponent.progressBindingOf(node, a)
                Reading(key, DynamicProgressComponent.progressValueOf(node, a, data, key))
            }
            "SelectBox" -> SelectBoxAttributes.parse(m).let { a ->
                if (isDate(node)) {
                    val key = DynamicSelectBoxComponent.dateBindingVariableOf(a)
                    Reading(key, DynamicSelectBoxComponent.dateSelectionOf(a, data, key))
                } else {
                    val key = DynamicSelectBoxComponent.bindingVariableOf(a)
                    Reading(key, DynamicSelectBoxComponent.selectionOf(a, data, DynamicSelectBoxComponent.parseOptions(node, data)))
                }
            }
            // The options group reads its bound key and that key's String
            // (createRadioGroup's reading, inline in the composable).
            "Radio" -> RadioAttributes.parse(m).let { a ->
                val key = DynamicRadioComponent.bindingVariableOf(a)
                Reading(key, key?.let { data[it] as? String } ?: "")
            }
            // The field reads its `text` — bound: the key it writes back and
            // the data value; static: the text (a model of its reading: the
            // resolution goes through a Context).
            "TextField" -> TextFieldAttributes.parse(m).let { a ->
                val key = TypedAttrs.binding(a.text)
                Reading(key, key?.let { data[it] } ?: TypedAttrs.static(a.text))
            }
            "TextView" -> TextViewAttributes.parse(m).let { a ->
                val key = TypedAttrs.binding(a.text)
                Reading(key, key?.let { data[it] } ?: TypedAttrs.static(a.text))
            }
            else -> error("no reading for ${node.get("type")}")
        }
    }

    /**
     * Over every section the table names and each of its value attributes
     * (the generated table's lists), plus the alias sections and a
     * Date SelectBox: a lone `bind` is the key the component writes and the
     * value it draws; beside a static own value, the component draws the
     * static value and writes nowhere; beside a bound one, the own binding.
     */
    @Test
    fun theFoldedNodeBindsEachComponentThroughItsOwnAttribute() {
        val sections = listOf(
            "Switch", "Toggle", "CheckBox", "Check", "Slider", "Segment", "Progress", "SelectBox", "SelectBox:Date",
            "Radio", "TextField", "TextView",
        )
        val found = mutableListOf<String>()
        var compared = 0
        for (section in sections) {
            val type = section.substringBefore(":")
            val shape = when {
                section.endsWith(":Date") -> json("""{"selectItemType": "Date"}""")
                type == "SelectBox" -> json("""{"items": ["a", "b"]}""")
                type == "Radio" -> json("""{"options": ["a", "b"]}""")
                else -> JsonObject()
            }.apply { addProperty("type", type) }
            val attrs = JsonUIBindPrimaryValue.attributesFor(type, TypedAttrs.toAttrMap(shape))
            assertTrue("$section names no value attribute", attrs.isNotEmpty())
            val (v1, v2, static) = values(type, isDate(shape))
            fun node(vararg entries: Pair<String, JsonElement>) = shape.deepCopy().apply { entries.forEach { (k, v) -> add(k, v) } }
            val bind = JsonParser.parseString("\"@{b}\"")

            // a lone bind: the key is b, and the drawn value follows b
            val lone = fold(node("bind" to bind))
            for (v in listOf(v1, v2)) {
                val r = read(lone, mapOf("b" to v))
                if (r.key != "b" || r.value != drawnOf(v)) found += "$section lone bind, b=$v: $r"
            }
            compared++
            for (attr in attrs) {
                val s = static(attr)
                val beside = fold(node(attr to s, "bind" to bind))
                val r = read(beside, mapOf("b" to v1))
                val alone = read(node(attr to s), mapOf("b" to v1))
                if (r != alone || r.key != null) found += "$section static $attr beside bind: $r, alone $alone"
                val own = fold(node(attr to JsonParser.parseString("\"@{own}\""), "bind" to bind))
                val ro = read(own, mapOf("own" to ownValue(attr, v2), "b" to v1))
                if (ro.key != "own") found += "$section bound $attr beside bind: $ro"
                compared += 2
            }
        }
        assertTrue("the sweep compared too few ($compared)", compared >= 30)
        assertEquals(found.joinToString("\n"), emptyList<String>(), found)
    }

    private fun drawnOf(v: Any): Any = if (v is Double) v.toFloat() else v

    /** Two values of the bound variable's type, and a static value per attribute, apart from them. */
    private fun values(type: String, date: Boolean): Triple<Any, Any, (String) -> JsonElement> = when (type) {
        "Switch", "Toggle", "CheckBox", "Check" -> Triple(true, false, { _: String -> JsonParser.parseString("true") })
        "Slider" -> Triple(0.25f, 0.75f, { _: String -> JsonParser.parseString("0.5") })
        "Progress" -> Triple(0.25f, 0.75f, { _: String -> JsonParser.parseString("0.5") })
        "Segment" -> Triple(2, 3, { _: String -> JsonParser.parseString("1") })
        "Radio", "TextField", "TextView" -> Triple("x", "y", { _: String -> JsonParser.parseString("\"note\"") })
        else -> if (date) {
            Triple("2026-02-02", "2026-03-03", { _: String -> JsonParser.parseString("\"2026-01-01\"") })
        } else {
            Triple("x", "y", { attr: String -> JsonParser.parseString(if (attr == "selectedIndex") "1" else "\"b\"") })
        }
    }

    private fun ownValue(attr: String, v: Any): Any = if (attr == "selectedIndex") 0 else v

    /**
     * DynamicView folds the node every built-in component draws — after the
     * synonym is resolved (the type the table is looked up by), before the
     * dispatch reads it — and hands an app's own component its node as
     * written. (A source-order read: the call site is a composable.)
     */
    @Test
    fun dynamicViewFoldsTheDrawnNodeBeforeTheDispatch_notAnAppsComponent() {
        val view = File("src/main/kotlin/com/kotlinjsonui/dynamic/DynamicView.kt").readText()
        val app = view.indexOf("Configuration.customComponentHandler?.invoke(type, responsiveJson, effectiveData)")
        val synonym = view.indexOf("TypeSynonyms.canonicalize(responsiveJson, context)")
        val fold = view.indexOf("val drawn = if (handledByApp) synonymous else BindFold.fold(synonymous, synonymous.get(\"type\").asString)")
        val dispatch = view.indexOf("if (!handledByApp) when (drawnType)")
        assertTrue("app $app < synonym $synonym < fold $fold < dispatch $dispatch",
            app in 0 until synonym && synonym < fold && fold < dispatch)
        // every built-in case draws `drawn`
        val cases = Regex("""-> Dynamic\w+Component\.create\((\w+), effectiveData\)""").findAll(view.substring(dispatch)).map { it.groupValues[1] }.toList()
        assertTrue("too few cases (${cases.size})", cases.size >= 27)
        assertEquals(setOf("drawn"), cases.toSet())
    }

    /**
     * No component reads `bind` (DynamicView folds it; Radio, TextField and
     * TextView are in the table too). Code only — a comment naming `bind`
     * does not count.
     */
    @Test
    fun noComponentReadsBind() {
        val token = Regex("""common\.bind|"bind"""")
        fun hits(text: String, name: String): List<String> = text.lines().mapIndexedNotNull { i, line ->
            val t = line.trimStart()
            if (t.startsWith("//") || t.startsWith("*") || t.startsWith("/*")) null
            else if (token.containsMatchIn(line.substringBefore("//"))) "$name:${i + 1}" else null
        }
        // the scan tells a read from a comment (both sides)
        assertEquals(1, hits("            ?: TypedAttrs.binding(a.common.bind)", "read").size)
        assertEquals(1, hits("""            "value", "bind", "enabled",""", "applied").size)
        assertEquals(0, hits("         * `bind` never reaches here (a.common.bind)\n        // \"bind\"", "comment").size)

        val root = File("src/main/kotlin/com/kotlinjsonui/dynamic/components")
        val files = root.listFiles { f -> f.extension == "kt" }!!.sortedBy { it.name }
        assertTrue("the scan reads too few files (${files.size})", files.size >= 27)
        val found = files.flatMap { hits(it.readText(), it.name) }
        assertEquals(emptyList<String>(), found)
    }
}
