package com.kotlinjsonui.conformance

import androidx.compose.runtime.Composable

/**
 * Compile-time default for the codegen fixture registry. The REAL registry
 * is @generated by scripts/generate_codegen_host.rb into
 * src/codegen/kotlin/... (gitignored); build.gradle.kts compiles EITHER that
 * source set OR this fallback — never both. Without the generated output the
 * host still builds, and a codegen-mode run reports every fixture as a
 * render error instead of hanging.
 */
object CodegenFixtureEntries {
    val map: Map<String, @Composable () -> Unit> = emptyMap()
}
