// Pasted from what `kjui build` (kjui_tools of jsonui-cli train/1.9.11 = 5447c616) emits for three Collections
// of conformance_cell cells — cellIdProperty "cellId", "key", and "cellId" with autoChangeTrackingId — and the
// cell view and view model it scaffolds, for CellDataRefreshProbeTest (jsonui-cli ticket
// ios-cell-ignores-data-change-when-cellid-is-fixed-android-updates). Changed from the output: the packages
// (com.kotlinjsonui.probe.* → com.kotlinjsonui.conformance.celldatarefresh) and the cell's two colorResource(R.color.…)
// (the probe project's resources) → the literal colors conformance_cell.json declares.
// Generated by kjui_tools - DO NOT EDIT between GENERATED_CODE markers
package com.kotlinjsonui.conformance.celldatarefresh

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update

class ConformanceCellViewModel(application: Application) : AndroidViewModel(application) {
    // JSON file reference for hot reload
    val jsonFileName = "conformance_cell"

    // Data model
    private val _data = MutableStateFlow(ConformanceCellData())
    val data: StateFlow<ConformanceCellData> = _data.asStateFlow()

    // >>> GENERATED_CODE_START
    // Auto-generated updateData function - updated by 'kjui build'
    fun updateData(updates: Map<String, Any>) {
        _data.update { current ->
            var updated = current
            updates.forEach { (key, value) ->
                updated = when (key) {
                    "title" -> updated.copy(title = value as? String ?: updated.title)
                    else -> updated
                }
            }
            updated
        }
    }
    // >>> GENERATED_CODE_END

    // Add your custom action handlers below
    fun onGetStarted() {
        // Handle button tap
    }
}
