// Generated by kjui_tools - DO NOT EDIT
package com.example.kotlinjsonui.sample.data


data class BasicCellData(
    var title: String = "Basic Item",
    var subtitle: String = "Description"
) {
    companion object {
        // Update properties from map
        fun fromMap(map: Map<String, Any>): BasicCellData {
            return BasicCellData(
                title = map["title"] as? String ?: "",
                subtitle = map["subtitle"] as? String ?: ""
            )
        }
    }

    // Convert properties to map for runtime use
    fun toMap(): MutableMap<String, Any> {
        val map = mutableMapOf<String, Any>()
        
        // Data properties
        map["title"] = title
        map["subtitle"] = subtitle
        
        return map
    }
}
