// Generated by kjui_tools - DO NOT EDIT
package com.example.kotlinjsonui.sample.data


data class ButtonEnabledTestData(
    var dynamicModeStatus: String = "OFF",
    var isButtonEnabled: Boolean = true,
    var title: String = "Button Enabled Test"
) {
    companion object {
        // Update properties from map
        fun fromMap(map: Map<String, Any>): ButtonEnabledTestData {
            return ButtonEnabledTestData(
                dynamicModeStatus = map["dynamicModeStatus"] as? String ?: "",
                isButtonEnabled = map["isButtonEnabled"] as? Boolean ?: false,
                title = map["title"] as? String ?: ""
            )
        }
    }

    // Convert properties to map for runtime use
    fun toMap(): MutableMap<String, Any> {
        val map = mutableMapOf<String, Any>()
        
        // Data properties
        map["dynamicModeStatus"] = dynamicModeStatus
        map["isButtonEnabled"] = isButtonEnabled
        map["title"] = title
        
        return map
    }
}
