// Generated by kjui_tools - DO NOT EDIT
package com.example.kotlinjsonui.sample.data


data class CollectionTestData(
    var dynamicModeEnabled: Boolean = false,
    var dynamicModeStatus: String = "OFF",
    var items1: com.kotlinjsonui.data.CollectionDataSource = com.kotlinjsonui.data.CollectionDataSource(),
    var mixedItems: com.kotlinjsonui.data.CollectionDataSource = com.kotlinjsonui.data.CollectionDataSource(),
    var horizontalItems: com.kotlinjsonui.data.CollectionDataSource = com.kotlinjsonui.data.CollectionDataSource(),
    var sectionedItems: com.kotlinjsonui.data.CollectionDataSource = com.kotlinjsonui.data.CollectionDataSource(),
    var multiSectionItems: com.kotlinjsonui.data.CollectionDataSource = com.kotlinjsonui.data.CollectionDataSource()
) {
    companion object {
        // Update properties from map
        fun fromMap(map: Map<String, Any>): CollectionTestData {
            return CollectionTestData(
                dynamicModeEnabled = map["dynamicModeEnabled"] as? Boolean ?: false,
                dynamicModeStatus = map["dynamicModeStatus"] as? String ?: "",
                items1 = com.kotlinjsonui.data.CollectionDataSource(),
                mixedItems = com.kotlinjsonui.data.CollectionDataSource(),
                horizontalItems = com.kotlinjsonui.data.CollectionDataSource(),
                sectionedItems = com.kotlinjsonui.data.CollectionDataSource(),
                multiSectionItems = com.kotlinjsonui.data.CollectionDataSource()
            )
        }
    }

    // Convert properties to map for runtime use
    fun toMap(): MutableMap<String, Any> {
        val map = mutableMapOf<String, Any>()
        
        // Data properties
        map["dynamicModeEnabled"] = dynamicModeEnabled
        map["dynamicModeStatus"] = dynamicModeStatus
        map["items1"] = items1
        map["mixedItems"] = mixedItems
        map["horizontalItems"] = horizontalItems
        map["sectionedItems"] = sectionedItems
        map["multiSectionItems"] = multiSectionItems
        
        return map
    }
}
