// Generated by kjui_tools - DO NOT EDIT
package com.example.kotlinjsonui.sample.data


data class ConverterTestCellData(
    var item: Map<String, Any> = emptyMap()
) {
    companion object {
        // Update properties from map
        fun fromMap(map: Map<String, Any>): ConverterTestCellData {
            return ConverterTestCellData(
                item = map["item"] as? Map<String, Any> ?: emptyMap()
            )
        }
    }

    // Convert properties to map for runtime use
    fun toMap(): MutableMap<String, Any> {
        val map = mutableMapOf<String, Any>()
        
        // Data properties
        map["item"] = item
        
        return map
    }
}
