// Generated by kjui_tools - DO NOT EDIT
package com.example.kotlinjsonui.sample.data


data class Included1Data(
    var title: String = "Included1"
) {
    companion object {
        // Update properties from map
        fun fromMap(map: Map<String, Any>): Included1Data {
            return Included1Data(
                title = map["title"] as? String ?: ""
            )
        }
    }

    // Convert properties to map for runtime use
    fun toMap(): MutableMap<String, Any> {
        val map = mutableMapOf<String, Any>()
        
        // Data properties
        map["title"] = title
        
        return map
    }
}
