// Generated by kjui_tools - DO NOT EDIT
package com.example.kotlinjsonui.sample.data


data class IncludeTestData(
    var dynamicModeStatus: String = "OFF",
    var mainCount: Int = 100,
    var mainStatus: String = "Main Active",
    var title: String = "Include Component Test",
    var userName: String = "Test User"
) {
    companion object {
        // Update properties from map
        fun fromMap(map: Map<String, Any>): IncludeTestData {
            return IncludeTestData(
                dynamicModeStatus = map["dynamicModeStatus"] as? String ?: "",
                mainCount = (map["mainCount"] as? Number)?.toInt() ?: 0,
                mainStatus = map["mainStatus"] as? String ?: "",
                title = map["title"] as? String ?: "",
                userName = map["userName"] as? String ?: ""
            )
        }
    }

    // Convert properties to map for runtime use
    fun toMap(): MutableMap<String, Any> {
        val map = mutableMapOf<String, Any>()
        
        // Data properties
        map["dynamicModeStatus"] = dynamicModeStatus
        map["mainCount"] = mainCount
        map["mainStatus"] = mainStatus
        map["title"] = title
        map["userName"] = userName
        
        return map
    }
}
