// Generated by kjui_tools - DO NOT EDIT
package com.example.kotlinjsonui.sample.data


data class MarginsTestData(
    var dynamicModeStatus: String = "OFF",
    var title: String = "Margins & Padding Test"
) {
    companion object {
        // Update properties from map
        fun fromMap(map: Map<String, Any>): MarginsTestData {
            return MarginsTestData(
                dynamicModeStatus = map["dynamicModeStatus"] as? String ?: "",
                title = map["title"] as? String ?: ""
            )
        }
    }

    // Convert properties to map for runtime use
    fun toMap(): MutableMap<String, Any> {
        val map = mutableMapOf<String, Any>()
        
        // Data properties
        map["dynamicModeStatus"] = dynamicModeStatus
        map["title"] = title
        
        return map
    }
}
