// Generated by kjui_tools - DO NOT EDIT
package com.example.kotlinjsonui.sample.data


data class SectionFooterData(
    var text: String = "End of section"
) {
    companion object {
        // Update properties from map
        fun fromMap(map: Map<String, Any>): SectionFooterData {
            return SectionFooterData(
                text = map["text"] as? String ?: ""
            )
        }
    }

    // Convert properties to map for runtime use
    fun toMap(): MutableMap<String, Any> {
        val map = mutableMapOf<String, Any>()
        
        // Data properties
        map["text"] = text
        
        return map
    }
}
