// Generated by kjui_tools - DO NOT EDIT
package com.example.kotlinjsonui.sample.data


data class TestMenuData(
    var dynamicModeStatus: String = "OFF"
) {
    companion object {
        // Update properties from map
        fun fromMap(map: Map<String, Any>): TestMenuData {
            return TestMenuData(
                dynamicModeStatus = map["dynamicModeStatus"] as? String ?: ""
            )
        }
    }

    // Convert properties to map for runtime use
    fun toMap(): MutableMap<String, Any> {
        val map = mutableMapOf<String, Any>()
        
        // Data properties
        map["dynamicModeStatus"] = dynamicModeStatus
        
        return map
    }
}
