// Generated by kjui_tools - DO NOT EDIT
package com.example.kotlinjsonui.sample.data


data class UserProfileTestData(
    var userName: String = "John Doe",
    var userEmail: String = "john.doe@example.com",
    var userAvatar: String = "https://i.pravatar.cc/150?img=1",
    var isOnline: Boolean = true,
    var userStatus: String = "Active",
    var notificationCount: Int = 5
) {
    companion object {
        // Update properties from map
        fun fromMap(map: Map<String, Any>): UserProfileTestData {
            return UserProfileTestData(
                userName = map["userName"] as? String ?: "",
                userEmail = map["userEmail"] as? String ?: "",
                userAvatar = map["userAvatar"] as? String ?: "",
                isOnline = map["isOnline"] as? Boolean ?: false,
                userStatus = map["userStatus"] as? String ?: "",
                notificationCount = (map["notificationCount"] as? Number)?.toInt() ?: 0
            )
        }
    }

    // Convert properties to map for runtime use
    fun toMap(): MutableMap<String, Any> {
        val map = mutableMapOf<String, Any>()
        
        // Data properties
        map["userName"] = userName
        map["userEmail"] = userEmail
        map["userAvatar"] = userAvatar
        map["isOnline"] = isOnline
        map["userStatus"] = userStatus
        map["notificationCount"] = notificationCount
        
        return map
    }
}
