// Generated by kjui_tools - DO NOT EDIT
package com.example.kotlinjsonui.sample.data


data class VisibilityTestData(
    var dynamicModeStatus: String = "OFF",
    var title: String = "Visibility & Opacity Test",
    var textVisibility: String = "visible",
    var isHidden: Boolean = false
) {
    companion object {
        // Update properties from map
        fun fromMap(map: Map<String, Any>): VisibilityTestData {
            return VisibilityTestData(
                dynamicModeStatus = map["dynamicModeStatus"] as? String ?: "",
                title = map["title"] as? String ?: "",
                textVisibility = map["textVisibility"] as? String ?: "",
                isHidden = map["isHidden"] as? Boolean ?: false
            )
        }
    }

    // Convert properties to map for runtime use
    fun toMap(): MutableMap<String, Any> {
        val map = mutableMapOf<String, Any>()
        
        // Data properties
        map["dynamicModeStatus"] = dynamicModeStatus
        map["title"] = title
        map["textVisibility"] = textVisibility
        map["isHidden"] = isHidden
        
        return map
    }
}
