package com.example.kotlinjsonui.sample.dynamic

import androidx.compose.runtime.Composable
import com.google.gson.JsonObject
import com.example.kotlinjsonui.sample.dynamic.components.extensions.DynamicSampleCardComponent
import com.example.kotlinjsonui.sample.dynamic.components.extensions.DynamicStatusBadgeComponent
import com.example.kotlinjsonui.sample.dynamic.components.extensions.DynamicUserAvatarComponent

/**
 * Registry for dynamic custom components
 * Auto-generated by kjui converter generator
 */
object DynamicComponentRegistry {
    @Composable
    fun createCustomComponent(
        type: String,
        json: JsonObject,
        data: Map<String, Any>
    ): Boolean {
        return when (type) {
            "SampleCard" -> {
                DynamicSampleCardComponent.create(json, data)
                true
            }
            "StatusBadge" -> {
                DynamicStatusBadgeComponent.create(json, data)
                true
            }
            "UserAvatar" -> {
                DynamicUserAvatarComponent.create(json, data)
                true
            }
            else -> false
        }
    }
}
