package com.example.kotlinjsonui.sample.dynamic

import androidx.compose.runtime.Composable
import com.google.gson.JsonObject
import com.kotlinjsonui.dynamic.components.*
import com.kotlinjsonui.dynamic.components.extensions.Dynamic--helpComponent
import com.kotlinjsonui.dynamic.components.extensions.DynamicStatusBadgeComponent
import com.example.kotlinjsonui.sample.dynamic.components.extensions.DynamicSampleCardComponent

/**
 * Registry for dynamic custom components
 * Auto-generated by kjui converter generator
 */
object DynamicComponentRegistry {
    @Composable
    fun createCustomComponent(
        type: String,
        json: JsonObject,
        data: Map<String, Any>
    ): Boolean {
        return when (type) {
            "SampleCard" -> {
                extensions.DynamicSampleCardComponent.create(json, data)
                true
            }
            "StatusBadge" -> extensions.DynamicStatusBadgeComponent.create(json, data)
            "--help" -> extensions.Dynamic--helpComponent.create(json, data)
            else -> false
        }
    }
}
