// Pasted from what `kjui build` (kjui_tools of jsonui-cli triage/static-valued-controls 46b7d599 on
// rel/v1.8.121) emits for four SelectBoxes bound to the data — selectedItem, selectedValue, selectedDate,
// selectedIndex — for ticket selectbox-selected-item-binding-is-read-once. Changed from the output: the
// package (com.kotlinjsonui.probe.* → com.kotlinjsonui.conformance.staticvalued) and the unused
// `import com.kotlinjsonui.probe.R`.
// Generated by kjui_tools - DO NOT EDIT between GENERATED_CODE markers
package com.kotlinjsonui.conformance.staticvalued

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update

class BoundSelectsViewModel(application: Application) : AndroidViewModel(application) {
    // JSON file reference for hot reload
    val jsonFileName = "bound_selects"

    // Data model
    private val _data = MutableStateFlow(BoundSelectsData())
    val data: StateFlow<BoundSelectsData> = _data.asStateFlow()

    // >>> GENERATED_CODE_START
    // Auto-generated updateData function - updated by 'kjui build'
    fun updateData(updates: Map<String, Any>) {
        _data.update { current ->
            var updated = current
            updates.forEach { (key, value) ->
                updated = when (key) {
                    "sbiSel" -> updated.copy(sbiSel = value as? String ?: updated.sbiSel)
                    "sbvSel" -> updated.copy(sbvSel = value as? String ?: updated.sbvSel)
                    "sbdDate" -> updated.copy(sbdDate = value as? String ?: updated.sbdDate)
                    "sbIdx" -> updated.copy(sbIdx = (value as? Number)?.toInt() ?: updated.sbIdx)
                    else -> updated
                }
            }
            updated
        }
    }
    // >>> GENERATED_CODE_END

    // Add your custom action handlers below
    fun onGetStarted() {
        // Handle button tap
    }
}
