// Pasted from what `kjui build` (kjui_tools of jsonui-cli rel/v1.8.121 = 24f7fad0) emits for
// DynamicStateProbeView's static layout (SwiftJsonUI ConformanceHost) — ticket
// static-valued-controls-do-not-change-on-a-users-tap. Changed from the output: the package
// (com.kotlinjsonui.probe.* → com.kotlinjsonui.conformance.staticvalued) and the unused
// `import com.kotlinjsonui.probe.R`; nothing else.
// Generated by kjui_tools - DO NOT EDIT between GENERATED_CODE markers
package com.kotlinjsonui.conformance.staticvalued

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update

class StaticControlsViewModel(application: Application) : AndroidViewModel(application) {
    // JSON file reference for hot reload
    val jsonFileName = "static_controls"

    // Data model
    private val _data = MutableStateFlow(StaticControlsData())
    val data: StateFlow<StaticControlsData> = _data.asStateFlow()

    // >>> GENERATED_CODE_START
    // Auto-generated updateData function - updated by 'kjui build'
    fun updateData(updates: Map<String, Any>) {
        _data.update { current ->
            var updated = current
            updates.forEach { (key, value) ->
                updated = when (key) {
                    else -> updated
                }
            }
            updated
        }
    }
    // >>> GENERATED_CODE_END

    // Add your custom action handlers below
    fun onGetStarted() {
        // Handle button tap
    }
}
