# frozen_string_literal: true

require_relative '../helpers/modifier_builder'

module KjuiTools
  module Compose
    module Components
      class GradientviewComponent
        def self.generate(json_data, depth, required_imports = nil, parent_type = nil)
          # GradientView maps to a Box with gradient background
          code = indent("Box(", depth)
          
          # Build modifiers
          modifiers = []
          modifiers.concat(Helpers::ModifierBuilder.build_size(json_data))
          modifiers.concat(Helpers::ModifierBuilder.build_padding(json_data))
          modifiers.concat(Helpers::ModifierBuilder.build_margins(json_data))
          
          # Add gradient background
          colors = json_data['colors'] || ['#000000', '#FFFFFF']
          start_point = json_data['startPoint'] || 'top'
          end_point = json_data['endPoint'] || 'bottom'
          
          # Determine gradient direction
          gradient_type = case [start_point, end_point]
          when ['top', 'bottom'], ['bottom', 'top']
            'verticalGradient'
          when ['left', 'right'], ['leading', 'trailing'], ['right', 'left'], ['trailing', 'leading']
            'horizontalGradient'
          else
            'linearGradient'
          end
          
          # Build color list
          color_list = colors.map { |color| "Color(android.graphics.Color.parseColor(\"#{color}\"))" }.join(", ")
          
          # Add gradient modifier
          required_imports&.add(:gradient)
          modifiers << ".background(Brush.#{gradient_type}(listOf(#{color_list})))"
          
          # Add corner radius if specified
          if json_data['cornerRadius']
            required_imports&.add(:shape)
            modifiers << ".clip(RoundedCornerShape(#{json_data['cornerRadius']}.dp))"
          end
          
          modifiers.concat(Helpers::ModifierBuilder.build_alignment(json_data, required_imports, parent_type))
          
          code += Helpers::ModifierBuilder.format(modifiers, depth)
          code += "\n" + indent(") {", depth)
          
          # Add child content if present
          if json_data['child']
            child_content = if json_data['child'].is_a?(Array)
              json_data['child']
            else
              [json_data['child']]
            end
            
            # Process children - they should be generated by the parent
            code += "\n" + indent("// Child content would be generated here", depth + 1)
          end
          
          code += "\n" + indent("}", depth)
          code
        end
        
        private
        
        def self.indent(text, level)
          return text if level == 0
          spaces = '    ' * level
          text.split("\n").map { |line| 
            line.empty? ? line : spaces + line 
          }.join("\n")
        end
      end
    end
  end
end