package com.example.kotlinjsonui.sample

/**
 * Release version of DynamicComponentInitializer (no-op)
 * Auto-generated by kjui converter generator
 */
object DynamicComponentInitializer {
    
    /**
     * No-op in release builds
     */
    fun initialize() {
        // Dynamic component registry is not available in release builds
    }
}
