// Pasted from what `kjui build` (kjui_tools of jsonui-cli 5447c616 + the sibling-locals fix, c38b15be) emits for three
// Collections of cell_refresh_probe_cell cells — cellIdProperty "cellId", "key", and "cellId" with
// autoChangeTrackingId, each in a View of its own — and the cell view and view model it scaffolds, for
// DynamicCellDataRefreshProbeTest (jsonui-cli ticket ios-cell-ignores-data-change-when-cellid-is-fixed-android-updates).
// Changed from the output: the packages (com.kotlinjsonui.probe.* → com.kotlinjsonui.dynamic.celldatarefresh).
// Generated by kjui_tools - DO NOT EDIT between GENERATED_CODE markers
package com.kotlinjsonui.dynamic.celldatarefresh

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update

class CellRefreshProbeCellViewModel(application: Application) : AndroidViewModel(application) {
    // JSON file reference for hot reload
    val jsonFileName = "cell_refresh_probe_cell"

    // Data model
    private val _data = MutableStateFlow(CellRefreshProbeCellData())
    val data: StateFlow<CellRefreshProbeCellData> = _data.asStateFlow()

    // >>> GENERATED_CODE_START
    // Auto-generated updateData function - updated by 'kjui build'
    fun updateData(updates: Map<String, Any>) {
        _data.update { current ->
            var updated = current
            updates.forEach { (key, value) ->
                updated = when (key) {
                    "title" -> updated.copy(title = value as? String ?: updated.title)
                    else -> updated
                }
            }
            updated
        }
    }
    // >>> GENERATED_CODE_END

    // Add your custom action handlers below
    fun onGetStarted() {
        // Handle button tap
    }
}
